<div class="tags-cloud" >
    <h1><?=Language::getText('tags_cloud')?></h1>
    <div class="tags-cloud-content">
        <?php if (isset($this->vars->tags_cloud)): ?>
            <?php foreach ($this->vars->tags_cloud as $tag): ?>
                <span class="tags-cloud-item<?=($tag->frequent ? ' frequent' : '')?>" ><a href="<?=HOST?>/search?<?=http_build_query(array('tag' => $tag->tagId))?>"><?=$tag->tag ?></a></span>
            <?php endforeach;?>
        <?php endif; ?>
    </div>
</div>