<?php
$this->addJs('jcycle.plugin.js');
$this->addJs('jcycle.js');
if (!$loggedInUser) $this->addSidebarBlock('home_login.phtml');
?>

<?php if ($logout): ?>
    <div class="message success"><?=Language::getText('success_logout')?></div>
<?php endif; ?>

<h1><?=Language::getText('home_header')?></h1>

<!-- BEGIN SLIDESHOW -->
<div id="slideshow">
    <!-- BEGIN FEATURED VIDEO SLIDES -->
    <?php foreach ($featured_videos as $featuredVideo): ?>
        <div>
            <img width="600" height="287" src="<?=$config->thumbUrl?>/<?=$featuredVideo->filename?>.jpg" />
            <div class="slide-text">
                <div>
                    <p class="large"><u><?=Language::getText('featured')?>:</u> <?=$featuredVideo->title?></p>
                    <p><?=Functions::cutOff($featuredVideo->description, 80)?></p>
                    <a class="button" href="<?=$this->getService('Video')->getUrl($featuredVideo)?>/">Watch Now</a>
                    
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <!-- END FEATURED VIDEO SLIDES -->
   
</div>
<!-- END SLIDESHOW -->
                    
<!-- SLIDESHOW SLIDE LINKS -->
<div id="slideshow_nav"></div>
                
<!-- BEGIN RECENT VIDEOS -->
<div class="recent_videos">

    <h1><?=Language::getText('recent_videos')?></h1>

    <div class="videos_list">
        <?php if (!empty ($recent_videos)): ?>
            <?php $this->repeatingBlock('video.phtml', $recent_videos); ?>
        <?php else: ?>
            <div class="block"><strong><?=Language::getText('no_videos')?></strong></div>
        <?php endif; ?>
    </div>

</div>
<!-- END RECENT VIDEOS --> 